### ISSUE TITLE
Checkbox overlaps part of the GUI

### ISSUE THREAD

**Issue by 825i** [MizukiBelhi/betterquest#1]
Hello, thanks for the addon. The GUI changed a little bit recently and the checkbox overlaps the GUI now.

You can see here (top left corner):

![GUI](https://i.imgur.com/zjpiH08.jpg)

**Comment by MizukiBelhi** [comment]
You seem to be using an old version. There should be a button not a checkbox.

**Comment by 825i** [comment]
This was downloaded from the ToS Addon Manager and the version number shows the exact same version as what is here on Github. If there is a newer version how is it available?

![tosaddonmanager](https://i.ibb.co/SyVhKFx/Screenshot-1.png)
