### ISSUE TITLE
Old version of BetterBetterQuest listed in ToS Addon Manager

### ISSUE THREAD

**Issue by 825i** [MizukiBelhi/betterquest#2]
This was downloaded from the ToS Addon Manager and the version number shows the exact same version as what is here on Github. If this is the old version then it needs to be replaced. I've checked the addon manager and it is pointing to the right repository. So either your code does not work and Issue #1 is valid, or an older version of your code is being downloaded and then this new issue needs fixing.

![tosaddonmanager](https://i.ibb.co/SyVhKFx/Screenshot-1.png)

_Originally posted by @pythonInRelay in https://github.com/MizukiBelhi/betterquest/issues/1#issuecomment-570939892_

**Comment by MizukiBelhi** [comment]
The only reason it would be different is if you have another older betterquest installed.
Check your data folder for betterquest files.
![37b5a2b74cf4df5ef5897a709e929c25](https://user-images.githubusercontent.com/19305926/72233786-38019280-357e-11ea-93ad-ef01d52f0a59.png)
